[tool.poetry]
name = "bottle-render"
version = "0.1.0"
description = ""
authors = ["Sergio Sanchez <barraquito@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bottle = "^0.12.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
